// packages/forge-genui-lit/src/renderer.ts
/**
 * ForgeGenUIRenderer Component
 *
 * A Lit element that renders a GenUISpec into actual DOM.
 *
 * How it works:
 * 1. Set spec property with a GenUISpec (typically from LLM tool output)
 * 2. Set registry property with component factories
 * 3. Component recursively renders from spec.root, looking up each element's
 *    type in the registry and calling its LitTemplateFactory
 * 4. Props with { $state: "/path" } are resolved to actual state values
 * 5. User interactions call emit() which dispatches forge-genui-action events
 *
 * The loading property shows a shimmer overlay while the LLM is generating.
 */

import { LitElement, html, nothing, unsafeCSS } from 'lit';
import type { PropertyValues, TemplateResult } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import {
  evaluateVisibility,
  resolveElementProps,
  createStateManager,
  type GenUISpec,
  type StateManager,
  type ActionEvent,
  type VisibilityCondition
} from '@tylertech/forge-genui-core';
import type { LitRegistry, LitComponentContext } from './types.js';

import styles from './renderer.scss?inline';

@customElement('forge-genui-renderer')
export class ForgeGenUIRenderer extends LitElement {
  public static override styles = unsafeCSS(styles);

  @property({ attribute: false })
  public spec: GenUISpec | null = null;

  @property({ attribute: false })
  public registry: LitRegistry | null = null;

  @property({ type: Boolean, reflect: true })
  public loading = false;

  @state()
  private _state: Record<string, unknown> = {};

  #stateManager: StateManager | null = null;

  protected override willUpdate(changedProperties: PropertyValues<this>): void {
    if (changedProperties.has('spec') && this.spec?.state) {
      this._state = { ...this.spec.state };
      this.#stateManager = this.#createStateManager();
    } else if (!this.#stateManager) {
      this.#stateManager = this.#createStateManager();
    }
  }

  #createStateManager(): StateManager {
    return createStateManager(this._state, () => {
      this._state = { ...this._state };
      this.requestUpdate();
    });
  }

  #emit = (action: string, payload?: Record<string, unknown>): void => {
    const event = new CustomEvent<ActionEvent>('forge-genui-action', {
      bubbles: true,
      composed: true,
      detail: {
        action,
        payload,
        state: { ...this._state }
      }
    });
    this.dispatchEvent(event);
  };

  #renderElement(elementId: string): TemplateResult | typeof nothing {
    if (!this.spec?.elements || !this.registry || !this.#stateManager) {
      return nothing;
    }

    const element = this.spec.elements[elementId];
    if (!element) {
      console.warn(`Element not found: ${elementId}`);
      return nothing;
    }

    if (element.visible && !this.#evaluateVisibility(element.visible as VisibilityCondition)) {
      return nothing;
    }

    const templateFn = this.registry.get(element.type);
    if (!templateFn) {
      console.warn(`Unknown component type: ${element.type}`);
      return nothing;
    }

    const resolvedProps = element.props
      ? resolveElementProps(element.props, { stateModel: this._state })
      : {};

    const children = element.children?.map(childId => this.#renderElement(childId)) ?? [];

    const context: LitComponentContext = {
      props: resolvedProps,
      children: children.length > 0 ? children : undefined,
      emit: this.#emit,
      state: this.#stateManager
    };

    return templateFn(context);
  }

  #evaluateVisibility(condition: VisibilityCondition): boolean {
    return evaluateVisibility(condition, { stateModel: this._state });
  }

  protected override render(): TemplateResult | typeof nothing {
    if (!this.spec?.root || !this.registry) {
      return nothing;
    }

    return html`
      ${this.#renderElement(this.spec.root)}
      <div class="loading-overlay"></div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'forge-genui-renderer': ForgeGenUIRenderer;
  }
}

// packages/gen-ui-demo/src/lib/renderer.tsx
import { useState, useCallback, useMemo, useEffect, Fragment } from 'react';
import type { ReactElement, ReactNode } from 'react';
import { evaluateVisibility, resolveElementProps } from '@json-render/core';
import {
  createStateManager,
  type GenUISpec,
  type StateManager,
  type ActionEvent,
  type Registry,
  type ComponentContext
} from '../core';

export interface GenUIRendererProps {
  spec: GenUISpec;
  registry: Registry<ReactNode, ReactNode>;
  onAction?: (event: ActionEvent) => void;
}

export function GenUIRenderer({ spec, registry, onAction }: GenUIRendererProps): ReactElement {
  const [stateModel, setStateModel] = useState<Record<string, unknown>>(() => spec.state ?? {});

  useEffect(() => {
    if (spec.state) {
      setStateModel({ ...spec.state });
    }
  }, [spec.state]);

  const stateManager: StateManager = useMemo(() => {
    return createStateManager(stateModel, () => {
      setStateModel(prev => ({ ...prev }));
    });
  }, [stateModel]);

  const emit = useCallback(
    (action: string, payload?: Record<string, unknown>): void => {
      onAction?.({
        action,
        payload,
        state: { ...stateModel }
      });
    },
    [onAction, stateModel]
  );

  const renderElement = useCallback(
    (elementId: string): ReactNode => {
      if (!spec.elements) {
        return null;
      }

      const element = spec.elements[elementId];
      if (!element) {
        console.warn(`Element not found: ${elementId}`);
        return null;
      }

      if (element.visible !== undefined && !evaluateVisibility(element.visible as Parameters<typeof evaluateVisibility>[0], { stateModel })) {
        return null;
      }

      const factory = registry.get({ type: element.type });
      if (!factory) {
        console.warn(`Unknown component type: ${element.type}`);
        return null;
      }

      const resolvedProps = element.props ? resolveElementProps(element.props, { stateModel }) : {};
      const children = element.children?.map(childId => renderElement(childId)) ?? [];

      const context: ComponentContext<ReactNode[]> = {
        props: resolvedProps,
        children: children.length > 0 ? children : [],
        emit,
        state: stateManager
      };

      return <Fragment key={elementId}>{factory(context)}</Fragment>;
    },
    [spec.elements, stateModel, registry, emit, stateManager]
  );

  if (!spec.root) {
    return <div className="genui-renderer" />;
  }

  return <div className="genui-renderer">{renderElement(spec.root)}</div>;
}
