// packages/forge-genui-react/src/components/button.tsx
import type { ReactElement } from 'react';
import { ForgeButton } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface ButtonProps {
  label?: string;
  variant?: 'text' | 'outlined' | 'tonal' | 'filled' | 'raised';
  disabled?: boolean;
  action?: string;
}

export function Button(ctx: ReactComponentContext<ButtonProps>): ReactElement | null {
  const { label = '', variant = 'raised', disabled = false, action } = ctx.props;

  if (!label) {
    return null;
  }

  const handleClick = (): void => {
    if (action) {
      ctx.emit(action);
    }
  };

  return (
    <ForgeButton variant={variant} disabled={disabled} onClick={handleClick}>
      {label}
    </ForgeButton>
  );
}

// packages/forge-genui-lit/src/components/button.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface ButtonProps {
  label?: string;
  variant?: 'text' | 'outlined' | 'tonal' | 'filled' | 'raised';
  disabled?: boolean;
  action?: string;
}

export function Button(ctx: LitComponentContext<ButtonProps>): TemplateResult | typeof nothing {
  const { label = '', variant = 'raised', disabled = false, action } = ctx.props;

  if (!label) {
    return nothing;
  }

  const handleClick = (): void => {
    if (action) {
      ctx.emit(action);
    }
  };

  return html`
    <forge-button
      variant=${variant}
      ?disabled=${disabled}
      @click=${handleClick}
    >
      ${label}
    </forge-button>
  `;
}
