// packages/agent-ui-react/src/demo/components/button.tsx
import type { ReactElement } from 'react';
import { ForgeButton } from '@tylertech/forge-react';
import { z } from 'zod';
import type { ComponentContext } from '@tylertech/agent-ui';

interface ButtonProps {
  label?: string;
  variant?: 'raised' | 'outlined' | 'text' | 'flat' | 'tonal';
  disabled?: boolean;
}

export function Button(ctx: ComponentContext<ButtonProps>): ReactElement {
  const { label = '', variant = 'raised', disabled = false } = ctx.props;

  return (
    <ForgeButton variant={variant} disabled={disabled} onClick={() => ctx.emit('click')}>
      {label}
    </ForgeButton>
  );
}

export const ButtonSchema = z.object({
  label: z.string().min(1).describe('Button text (required)'),
  variant: z.enum(['raised', 'outlined', 'text', 'flat', 'tonal']).describe('Button style variant').optional(),
  disabled: z.boolean().describe('Disable button').optional()
});

// packages/forge-genui-lit/src/components/button.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface ButtonProps {
  label?: string;
  variant?: 'text' | 'outlined' | 'tonal' | 'filled' | 'raised';
  disabled?: boolean;
  action?: string;
}

export function Button(ctx: LitComponentContext<ButtonProps>): TemplateResult | typeof nothing {
  const { label = '', variant = 'raised', disabled = false, action } = ctx.props;

  if (!label) {
    return nothing;
  }

  const handleClick = (): void => {
    if (action) {
      ctx.emit(action);
    }
  };

  return html`
    <forge-button
      variant=${variant}
      ?disabled=${disabled}
      @click=${handleClick}
    >
      ${label}
    </forge-button>
  `;
}
