// packages/forge-genui-react/src/components/card.tsx
import type { ReactElement } from 'react';
import { ForgeCard } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface CardProps {
  raised?: boolean;
}

export function Card(ctx: ReactComponentContext<CardProps>): ReactElement | null {
  const { raised = false } = ctx.props;

  return <ForgeCard raised={raised}>{ctx.children}</ForgeCard>;
}

// packages/forge-genui-lit/src/components/card.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface CardProps {
  raised?: boolean;
}

export function Card(ctx: LitComponentContext<CardProps>): TemplateResult | typeof nothing {
  const { raised = false } = ctx.props;

  return html`<forge-card ?raised=${raised}>${ctx.children}</forge-card>`;
}
