// packages/forge-genui-react/src/components/list-item.tsx
import type { ReactElement } from 'react';
import { ForgeListItem } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface ListItemProps {
  text?: string;
  secondaryText?: string;
  tertiaryText?: string;
  selected?: boolean;
  value?: string;
  action?: string;
}

export function ListItem(ctx: ReactComponentContext<ListItemProps>): ReactElement | null {
  const { text = '', secondaryText, tertiaryText, selected = false, value, action } = ctx.props;

  if (!text) {
    return null;
  }

  const handleClick = (): void => {
    if (action) {
      ctx.emit(action, { value });
    }
  };

  return (
    <ForgeListItem selected={selected} value={value ?? ''} onClick={handleClick}>
      {text}
      {secondaryText && <span slot="secondary-text">{secondaryText}</span>}
      {tertiaryText && <span slot="tertiary-text">{tertiaryText}</span>}
    </ForgeListItem>
  );
}

// packages/forge-genui-lit/src/components/list-item.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface ListItemProps {
  text?: string;
  secondaryText?: string;
  tertiaryText?: string;
  selected?: boolean;
  value?: string;
  action?: string;
}

export function ListItem(ctx: LitComponentContext<ListItemProps>): TemplateResult | typeof nothing {
  const { text = '', secondaryText, tertiaryText, selected = false, value, action } = ctx.props;

  if (!text) {
    return nothing;
  }

  const handleClick = (): void => {
    if (action) {
      ctx.emit(action, { value });
    }
  };

  return html`
    <forge-list-item
      ?selected=${selected}
      .value=${value ?? ''}
      @click=${handleClick}
    >
      ${text}
      ${secondaryText ? html`<span slot="secondary-text">${secondaryText}</span>` : nothing}
      ${tertiaryText ? html`<span slot="tertiary-text">${tertiaryText}</span>` : nothing}
    </forge-list-item>
  `;
}
