// packages/forge-genui-react/src/components/list.tsx
import type { ReactElement } from 'react';
import { ForgeList } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface ListProps {
  dense?: boolean;
  twoLine?: boolean;
  threeLine?: boolean;
}

export function List(ctx: ReactComponentContext<ListProps>): ReactElement | null {
  const { dense = false, twoLine = false, threeLine = false } = ctx.props;

  if (!ctx.children || ctx.children.length === 0) {
    return null;
  }

  return (
    <ForgeList dense={dense} twoLine={twoLine} threeLine={threeLine}>
      {ctx.children}
    </ForgeList>
  );
}

// packages/forge-genui-lit/src/components/list.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface ListProps {
  dense?: boolean;
  twoLine?: boolean;
  threeLine?: boolean;
}

export function List(ctx: LitComponentContext<ListProps>): TemplateResult | typeof nothing {
  const { dense = false, twoLine = false, threeLine = false } = ctx.props;

  if (!ctx.children || ctx.children.length === 0) {
    return nothing;
  }

  return html`
    <forge-list
      ?dense=${dense}
      ?two-line=${twoLine}
      ?three-line=${threeLine}
    >
      ${ctx.children}
    </forge-list>
  `;
}
