// packages/forge-genui-react/src/components/text-field.tsx
import type { ReactElement, ChangeEvent } from 'react';
import { ForgeTextField } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface TextFieldProps {
  label?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  binding?: string;
}

export function TextField(ctx: ReactComponentContext<TextFieldProps>): ReactElement | null {
  const { label = '', value = '', placeholder, disabled = false, required = false, binding } = ctx.props;

  const handleInput = (event: ChangeEvent<HTMLInputElement>): void => {
    if (binding) {
      ctx.state.set(binding, event.target.value);
    }
  };

  return (
    <ForgeTextField>
      <label slot="label">{label}</label>
      <input
        type="text"
        value={value}
        placeholder={placeholder ?? ''}
        disabled={disabled}
        required={required}
        onChange={handleInput}
      />
    </ForgeTextField>
  );
}

// packages/forge-genui-lit/src/components/text-field.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface TextFieldProps {
  label?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  binding?: string;
}

export function TextField(ctx: LitComponentContext<TextFieldProps>): TemplateResult | typeof nothing {
  const { label = '', value = '', placeholder, disabled = false, required = false, binding } = ctx.props;

  const handleInput = (event: Event): void => {
    const input = event.target as HTMLInputElement;
    if (binding) {
      ctx.state.set(binding, input.value);
    }
  };

  return html`
    <forge-text-field>
      <label slot="label">${label}</label>
      <input
        type="text"
        .value=${value}
        placeholder=${placeholder ?? ''}
        ?disabled=${disabled}
        ?required=${required}
        @input=${handleInput}
      />
    </forge-text-field>
  `;
}
