// packages/forge-genui-lit/src/components/avatar.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface AvatarProps {
  text?: string;
  imageUrl?: string;
  letterCount?: number;
}

export function Avatar(ctx: LitComponentContext<AvatarProps>): TemplateResult | typeof nothing {
  const { text, imageUrl, letterCount = 2 } = ctx.props;

  if (!text && !imageUrl) {
    return nothing;
  }

  return html`
    <forge-avatar
      text=${text ?? ''}
      image-url=${imageUrl ?? ''}
      letter-count=${letterCount}
    ></forge-avatar>
  `;
}

// packages/forge-genui-react/src/components/avatar.tsx
import type { ReactElement } from 'react';
import { ForgeAvatar } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface AvatarProps {
  text?: string;
  imageUrl?: string;
  letterCount?: number;
}

export function Avatar(ctx: ReactComponentContext<AvatarProps>): ReactElement | null {
  const { text, imageUrl, letterCount = 2 } = ctx.props;

  if (!text && !imageUrl) {
    return null;
  }

  return <ForgeAvatar text={text ?? ''} imageUrl={imageUrl ?? ''} letterCount={letterCount} />;
}
