// packages/forge-genui-lit/src/components/checkbox.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface CheckBoxProps {
  label?: string;
  checked?: boolean;
  disabled?: boolean;
  action?: string;
  binding?: string;
}

export function CheckBox(ctx: LitComponentContext<CheckBoxProps>): TemplateResult | typeof nothing {
  const { label = '', checked = false, disabled = false, action, binding } = ctx.props;

  const handleChange = (event: Event): void => {
    const checkbox = event.target as HTMLInputElement;
    if (binding) {
      ctx.state.set(binding, checkbox.checked);
    }
    if (action) {
      ctx.emit(action, { checked: checkbox.checked });
    }
  };

  return html`
    <forge-checkbox ?disabled=${disabled}>
      <input
        type="checkbox"
        .checked=${checked}
        @change=${handleChange}
      />
      <label slot="label">${label}</label>
    </forge-checkbox>
  `;
}

// packages/forge-genui-react/src/components/checkbox.tsx
import type { ReactElement, ChangeEvent } from 'react';
import { ForgeCheckbox } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface CheckBoxProps {
  label?: string;
  checked?: boolean;
  disabled?: boolean;
  action?: string;
  binding?: string;
}

export function CheckBox(ctx: ReactComponentContext<CheckBoxProps>): ReactElement | null {
  const { label = '', checked = false, disabled = false, action, binding } = ctx.props;

  const handleChange = (event: ChangeEvent<HTMLInputElement>): void => {
    const isChecked = event.target.checked;
    if (binding) {
      ctx.state.set(binding, isChecked);
    }
    if (action) {
      ctx.emit(action, { checked: isChecked });
    }
  };

  return (
    <ForgeCheckbox disabled={disabled}>
      <input type="checkbox" checked={checked} onChange={handleChange} />
      <label slot="label">{label}</label>
    </ForgeCheckbox>
  );
}
