// packages/forge-genui-lit/src/components/divider.ts
import { html } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface DividerProps {
  vertical?: boolean;
}

export function Divider(ctx: LitComponentContext<DividerProps>): TemplateResult {
  const { vertical = false } = ctx.props;

  return html`<forge-divider ?vertical=${vertical}></forge-divider>`;
}

// packages/forge-genui-react/src/components/divider.tsx
import type { ReactElement } from 'react';
import { ForgeDivider } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface DividerProps {
  vertical?: boolean;
}

export function Divider(ctx: ReactComponentContext<DividerProps>): ReactElement {
  const { vertical = false } = ctx.props;

  return <ForgeDivider vertical={vertical} />;
}
