// packages/forge-genui-lit/src/components/inline-message.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface InlineMessageProps {
  title?: string;
  text?: string;
  theme?: 'info' | 'success' | 'warning' | 'error';
}

export function InlineMessage(ctx: LitComponentContext<InlineMessageProps>): TemplateResult | typeof nothing {
  const { title, text = '', theme = 'info' } = ctx.props;

  if (!text && !title) {
    return nothing;
  }

  return html`
    <forge-inline-message theme=${theme}>
      ${title ? html`<span slot="title">${title}</span>` : nothing}
      ${text}
    </forge-inline-message>
  `;
}

// packages/forge-genui-react/src/components/inline-message.tsx
import type { ReactElement } from 'react';
import { ForgeInlineMessage } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface InlineMessageProps {
  title?: string;
  text?: string;
  theme?: 'info' | 'success' | 'warning' | 'error';
}

export function InlineMessage(ctx: ReactComponentContext<InlineMessageProps>): ReactElement | null {
  const { title, text = '', theme = 'info' } = ctx.props;

  if (!text && !title) {
    return null;
  }

  return (
    <ForgeInlineMessage theme={theme}>
      {title && <span slot="title">{title}</span>}
      {text}
    </ForgeInlineMessage>
  );
}
