// packages/forge-genui-lit/src/components/toolbar.ts
import { html, nothing } from 'lit';
import type { TemplateResult } from 'lit';
import type { LitComponentContext } from '../types.js';

interface ToolbarProps {
  inverted?: boolean;
  noDivider?: boolean;
}

export function Toolbar(ctx: LitComponentContext<ToolbarProps>): TemplateResult | typeof nothing {
  const { inverted = false, noDivider = false } = ctx.props;

  if (!ctx.children || ctx.children.length === 0) {
    return nothing;
  }

  return html`
    <forge-toolbar
      ?inverted=${inverted}
      ?no-divider=${noDivider}
    >
      ${ctx.children}
    </forge-toolbar>
  `;
}

// packages/forge-genui-react/src/components/toolbar.tsx
import type { ReactElement } from 'react';
import { ForgeToolbar } from '@tylertech/forge-react';
import type { ReactComponentContext } from '../types.js';

interface ToolbarProps {
  inverted?: boolean;
  noDivider?: boolean;
}

export function Toolbar(ctx: ReactComponentContext<ToolbarProps>): ReactElement | null {
  const { inverted = false, noDivider = false } = ctx.props;

  if (!ctx.children || ctx.children.length === 0) {
    return null;
  }

  return (
    <ForgeToolbar inverted={inverted} noDivider={noDivider}>
      {ctx.children}
    </ForgeToolbar>
  );
}
